[package]
name = "dprint-plugin-markdown"
version = "0.11.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
homepage = "https://github.com/dprint/dprint-plugin-markdown"
license = "MIT"
repository = "https://github.com/dprint/dprint-plugin-markdown"
description = "Markdown formatter for dprint."

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"

[features]
wasm = ["serde_json", "dprint-core/wasm"]
tracing = ["dprint-core/tracing"]

[dependencies]
dprint-core = { version = "0.46.4", features = ["formatting"] }
pulldown-cmark = { version = "0.8.0", default-features = false }
regex = "1"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
dprint-development = "0.4.1"
serde_json = { version = "1.0" }
