[package]
name = "dprint-plugin-markdown"
description = "Markdown formatter for dprint."
version = "0.3.0"
authors = ["David Sherret <dsherret@gmail.com>"]
license-file = "LICENSE"
edition = "2018"
homepage = "https://github.com/dprint/dprint-plugin-markdown"
repository = "https://github.com/dprint/dprint-plugin-markdown"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"

[features]
wasm = ["serde_json", "dprint-core/wasm"]

[dependencies]
dprint-core = { version = "0.25.0", features = ["formatting"] }
lazy_static = "1.4.0"
pulldown-cmark = { version = "0.7.2", default-features = false }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
regex = "1"

[dev-dependencies]
dprint-development = "0.2.0"
