#!/usr/bin/env python3
"""Regenerate bundled dependency notices from locked Cargo source packages."""
import json
from pathlib import Path
import subprocess

root = Path(__file__).resolve().parent.parent
packages = {}
for target in ["x86_64-unknown-linux-gnu", "aarch64-linux-android"]:
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--locked", "--format-version", "1", "--filter-platform", target], cwd=root
    ))
    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    resolved = set()
    pending = [p["id"] for p in metadata["packages"] if p["name"] == "dprint-markdown-ja-formatter"]
    while pending:
        package_id = pending.pop()
        if package_id in resolved:
            continue
        resolved.add(package_id)
        pending.extend(dep["pkg"] for dep in nodes[package_id]["deps"]
                       if any(kind["kind"] != "dev" for kind in dep["dep_kinds"]))
    packages.update((p["id"], p) for p in metadata["packages"] if p["id"] in resolved)
parts = ["# Third-party notices\n\nGenerated by `python3 scripts/license-notices.py` from "
         "`Cargo.lock` for Linux x86-64 and Android ARM64, including build dependencies. "
         "Retain these notices with redistributed binaries and AARs.\n"]
for package in sorted(packages.values(), key=lambda p: (p["name"], p["version"])):
    if package["name"] == "dprint-markdown-ja-formatter":
        continue
    directory = Path(package["manifest_path"]).parent
    files = sorted(p for p in directory.iterdir() if p.is_file()
                   and p.name.upper().startswith(("LICENSE", "LICENCE", "COPYING", "COPYRIGHT", "NOTICE")))
    # This workspace subcrate omits its repository-root licenses from its tarball.
    if package["name"] == "jni-sys-macros":
        sibling = next(p for p in packages.values() if p["name"] == "jni-sys" and p["version"] == package["version"])
        files = sorted(Path(sibling["manifest_path"]).parent.glob("LICENSE*"))
    if not files:
        raise SystemExit(f"No license file found: {package['name']}")
    parts.append(f"\n## {package['name']} {package['version']}\n\n"
                 f"License: {package['license']}\n\nSource: {package['source'] or package['repository']}\n")
    for path in files:
        parts.append(f"\n### {path.name}\n\n```text\n{path.read_text().rstrip()}\n```\n")
    if package["name"] == "cesu8":
        # The crate ships a copyright file and source-header notice, but links
        # rather than bundles the MIT permission text. Include both here.
        header = "\n".join((directory / "src/lib.rs").read_text().splitlines()[:9])
        mit = (root / "LICENSE").read_text().split("Permission is hereby granted", 1)[1]
        parts.append(f"\n```text\n{header}\n\nPermission is hereby granted{mit}```\n")
output = root.parent / "target/THIRD_PARTY_NOTICES.md"
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("".join(parts))
print(f"Generated {output}")
